// <auto-generated />
namespace Inventory_Management_Systems.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _199 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_199));
        
        string IMigrationMetadata.Id
        {
            get { return "202002101752258_199"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
