// <auto-generated />
namespace Inventory_Management_Systems.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changeOrdertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeOrdertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202005011253222_changeOrdertable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
