// <auto-generated />
namespace Inventory_Management_Systems.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class additemk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(additemk));
        
        string IMigrationMetadata.Id
        {
            get { return "202008271607353_additemk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
